Repository Eoxia/priseo, pull requests merged in 2024-08, with the labels that each got.

#27 #26 [Mod] add: url in extrafield
  class/competitorprice.class.php
  core/modules/modPriseo.class.php
  langs/en_US/priseo.lang
  langs/fr_FR/priseo.lang
Labels: 1, Enhancement

#28 #21 [CompetitorPrice] add: filter on columns and modify order of the columns
  class/competitorprice.class.php
  view/competitorprice_card.php
Labels: 1, Enhancement

#35 #29 [Hook] add: number of competitor prices on tab
  class/actions_priseo.class.php
  core/modules/modPriseo.class.php
Labels: 2, Enhancement

#37 #36 [Hook] fix: function not available in v18 dolibarr
  class/actions_priseo.class.php
Labels: 0, Bug

#38 #32 [Rework] add: saturne
  admin/index.php
  admin/setup.php
  class/index.php
  core/modules/modPriseo.class.php
  core/modules/priseo/index.php
  index.php
  lib/index.php
  lib/priseo.lib.php
  priseo.main.inc.php
  view/competitorprice_card.php
  view/index.php
Labels: 2, Enhancement

#39 #30 [Competitorprice] add: clone system
  class/competitorprice.class.php
  view/competitorprice_card.php
Labels: 2, Enhancement

#42 #40 [CompetitorPrice] fix: sql bug of setCategories
  class/competitorprice.class.php
  view/competitorprice_card.php
Labels: 1, Bug

#43 #41 [Mod] add: new version number 1.1.0
  README.md
  core/modules/modPriseo.class.php
Labels: 0, Enhancement
